# Generated by Django 5.0.7 on 2024-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость аренды за час')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость аренды за день')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (в кг)')),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мощность (в л.с.)')),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Габариты (ДxШxВ в метрах)')),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип топлива')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъемность (в кг)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для аренды')),
                ('image', models.ImageField(blank=True, null=True, upload_to='technique_images/', verbose_name='Фото техники')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
            },
        ),
    ]
