# Generated by Django 5.0.7 on 2024-08-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technique',
            old_name='Name',
            new_name='name',
        ),
    ]
