# Generated by Django 5.0.8 on 2024-09-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniquePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='technique_photos/')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.technique')),
            ],
        ),
    ]
