# Generated by Django 5.0.7 on 2024-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_name_technique_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technique',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
