# Generated by Django 5.0.7 on 2024-08-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('start_date', models.DateField(verbose_name='Начало аренды')),
                ('end_date', models.DateField(verbose_name='Окончание аренды')),
                ('status', models.CharField(choices=[('accepted', 'Заказ принят'), ('rejected', 'Заказ отклонён'), ('in_progress', 'Заказ в работе'), ('completed', 'Заказ завершён')], default='accepted', max_length=20, verbose_name='Статус заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Общая стоимость аренды')),
                ('additional_requirements', models.TextField(blank=True, null=True, verbose_name='Доп. требования')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.technique', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
